services:
  postgresDb:
    container_name: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgresDb
    restart: always
    ports:
     - "5433:5432"
    volumes:
     - postgres:/var/lib/postgresql/data/
  
  distributedCache:
    container_name: redis
    restart: always
    ports:
    - "6379:6379"

  rebbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
       - mynetwork

networks:
  mynetwork:
    driver: bridge