services:
  postgresDb:
    image: postgres:latest
    
  distributedCache:
    image: redis:latest

  rabbitmq:
     image: rabbitmq:3-management


  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Application/Aggregator/API/Dockerfile

volumes:
    postgres: 
