services:
  postgresDb:
    container_name: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgresDb
    restart: always
    ports:
     - "5431:5432"
    volumes:
     - postgres:/var/lib/postgresql/data/
